### ISSUE TITLE
OMGGG

### ISSUE THREAD

**Issue by hyp3ri0n-ng** [TeamHG-Memex/sshadduser#1]
$ ps -p $$
  PID TTY          TIME CMD
 9163 pts/2    00:00:00 sh

MY DEFAULT SHELL IS SH THIS IS GOING TO KILL MY PRODUCTIVITY PLS FIX IMMEDIAATELY!!!!!!11!!one!!

**Comment by mehaase** [comment]
Closed this just in the nick of time. 

You can now finish whatever you were doing at 2016-10-04T:10:50:00Z+05:00

**Comment by hyp3ri0n-ng** [comment]
phew, thank god. I had something due at 2018-10-04T:16:08:03Z+05:00
